# тут надо покумекать

apiVersion: skaffold/v3beta1
kind: Config
metadata:
  name: pipe
build:
  artifacts:
    - image: al8trapeznikov/app-backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: al8trapeznikov/app-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/frontend-deployment.yaml
      - k8s/backend-deployment.yaml
      - k8s/pipe-ingress.yaml
portForward:
  - resourceType: service
    resourceName: frontend-service
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: backend-service
    port: 5000
    localPort: 5000